import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../styles/globals.css";
import "./../styles/reset.css";
import { NoScript } from "./no-script";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "scroll-smooth bg-background text-foreground antialiased",
          inter.className,
        )}
      >
        <Providers>
          <NoScript />
          {children}
        </Providers>
      </body>
    </html>
  );
}
